/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CanvasesCanvasIdImport } from './routes/canvases/$canvasId'

// Create/Update Routes

const CanvasesCanvasIdRoute = CanvasesCanvasIdImport.update({
  id: '/canvases/$canvasId',
  path: '/canvases/$canvasId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/canvases/$canvasId': {
      id: '/canvases/$canvasId'
      path: '/canvases/$canvasId'
      fullPath: '/canvases/$canvasId'
      preLoaderRoute: typeof CanvasesCanvasIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/canvases/$canvasId': typeof CanvasesCanvasIdRoute
}

export interface FileRoutesByTo {
  '/canvases/$canvasId': typeof CanvasesCanvasIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/canvases/$canvasId': typeof CanvasesCanvasIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/canvases/$canvasId'
  fileRoutesByTo: FileRoutesByTo
  to: '/canvases/$canvasId'
  id: '__root__' | '/canvases/$canvasId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CanvasesCanvasIdRoute: typeof CanvasesCanvasIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  CanvasesCanvasIdRoute: CanvasesCanvasIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/canvases/$canvasId"
      ]
    },
    "/canvases/$canvasId": {
      "filePath": "canvases/$canvasId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
